/*
 * Each new term in the Fibonacci sequence is generated by adding the previous 
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms.
 */
public class Problem2 {
    
    public static void main(String[] args) {
        
        int first = 1;
        int second = 2;
        int next = first + second;
        
        int upperLimit = Integer.parseInt(args[0]);
        int sum = second;
        
        while (next < upperLimit) {
            if (next % 2 == 0)
                sum += next;
            first = second;
            second = next;
            next = first + second;
        }
        
        System.out.println("The sum of the even-valued terms in the " +
                "Fibonacci sequence whose values do not exceed " +
                upperLimit + " is " + sum );
    }
}